services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - simple_blog   # 이미지 이름 설정
    image: simple_blog   # 직접 명시적으로 이미지 이름 지정
    ports:
      - "80:4000"
    volumes:
      - .:/srv/jekyll
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000
    environment:
      - JEKYLL_ENV=development
