resume_url: "Resume.pdf"
author_name: "MovingJu"
url: "movingju.com"
future: true
timezone: Asia/Seoul

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-assets
  - sprockets
  - autoprefixer-rails
  - jemoji

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
pagination:
  enabled: true
  debug: true
  collection: "posts"
  per_page: 10
  permalink: "/blog/:num/"
  title: ":title - page :num"
  limit: 10
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: "index"

############################################################
assets:
  source_maps: true
  destination: "/assets"
  compression: false
  gzip: false
  defaults:
    integrity:
      css: false
      img: false
      js: false
  caching:
    enabled: true
    path: ".jekyll-cache/assets"
    type: file
  precompile: []
  raw_precompile: []
  cdn:
    baseurl: ""
    destination: false
    url: ""
  sources:
    - _assets/custom
  plugins:
    css:
      autoprefixer: {}
    img:
      optim: {}

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

google_analytics: "UA_123456789_1"

disqus:
  shortname: "MovingJu"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    guess_lang: true
